# Generated by Django 3.1.3 on 2020-11-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20201119_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterSummary',
            new_name='Character',
        ),
    ]
