# Generated by Django 3.1.3 on 2020-11-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20201119_0911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorySummary',
            new_name='Story',
        ),
    ]
