# Generated by Django 3.1.3 on 2020-11-19 06:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0006_auto_20201119_0915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comic',
            new_name='SavedComic',
        ),
    ]
