# Generated by Django 3.1.3 on 2020-11-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20201119_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Обложка комикса', 'verbose_name_plural': 'Обложкиы комиксов'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='extension',
            new_name='version',
        ),
    ]
