# Generated by Django 3.1.3 on 2020-11-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20201119_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='version',
            new_name='extension',
        ),
    ]
