# Generated by Django 3.1.3 on 2020-11-19 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0009_auto_20201119_1723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedcomic',
            unique_together={('user', 'comic_id')},
        ),
    ]
