# Generated by Django 3.1.3 on 2020-11-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_auto_20201119_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcomic',
            name='release_date',
            field=models.DateField(verbose_name='Дата выхода'),
        ),
    ]
